### ISSUE TITLE
Branching Problem

### ISSUE THREAD

**Issue by Malix-Off** [scratch-for-discord/Web-Application_Frontend#165]
@RedMan13 what is https://github.com/scratch-for-discord/Web-Application_Frontend/tree/feature/toolbox/redman?
https://github.com/scratch-for-discord/Web-Application_Frontend/compare/release/2/master...scratch-for-discord:Web-Application_Frontend:feature/toolbox/redman

**Comment by RedMan13** [comment]
i have 0 idea

**Comment by RedMan13** [comment]
wait no i think its for like blocks and stuff

**Comment by RedMan13** [comment]
bc i was going to add blocks then just didnt

**Comment by Malix-Off** [comment]
@RedMan13 here is a comparative between release/2/master and this branch:
https://github.com/scratch-for-discord/Web-Application_Frontend/compare/release/2/master...scratch-for-discord:Web-Application_Frontend:feature/toolbox/redman
Please either delete feature/toolbox/redman, or open a pull request from it to release/2/master

**Comment by RedMan13** [comment]
yeah its just blocks that i never added
you can delete it theres nothing in there of use

**Comment by Malix-Off** [comment]
Okay
